<?php
	$title = 'Home';
?>
<h1>Home</h1>
<h2>Vaults</h2>
<?php if (!empty($vaults)) { ?>
<?php foreach($vaults as $id => $vault) { ?>
	<div class="card">
		<h3><?php print($vault -> name); ?></h3>
	<?php if (!empty($app -> getVaultKey($vault -> id))) { ?>
		<p>This vault is currently unlocked.</p>
		<a href="<?php $app -> url("vault/{$vault -> id}"); ?>" class="button">
			View Vault
		</a>
	<?php } else { ?>
		<form action="<?php $app -> url("vault/{$vault -> id}"); ?>" method="post">
			<label for="password-<?php print($id); ?>">Password</label>
			<input id="password-<?php print($id); ?>" name="password" type="password" />
			<input type="submit" value="Unlock" />
		</form>
	<?php } ?>
	</div>
<?php } ?>
<?php } else { ?>
<p>You have not created a vault yet.</p>
<?php } ?>
<h2>How-To Guide</h2>
<h3>How does this work?</h3>
<p>
	<?php print($app -> config['app']['name']); ?> allows you to organize and encrypt information, like credentials,
	or anything text-based.
	Instead of memorizing usernames and passwords for every account, <?php print($app -> config['app']['name']); ?>
	simplifies this to only a handful of passwords.
</p>
<p>
	Your account password is used to encrypt your vault information, and your vault passwords are used to encrypt
	your archives and records.
	If you forget these passwords, you'll lose access to all of the information contained within.
</p>
<h3>What are Vaults?</h3>
<p>
	Vaults are containers that allow you to organize and categorize large sets of data you want to encrypt.
	For instance, you might have a "personal" vault, and a "work" vault.
	It's really up to you, how best to categorize your information!
</p>
<p>
	Each vault is password protected and this password is very important!
	If you lose access to your vault password, you lose access to all of the data contained inside.
</p>
<h3>What are Archives and Records?</h3>
<p>
	Archives are smaller containers that exist within vaults.
	Each archive contains a collection of records, and each record contains specific information you want to encrypt.
	If you have a "personal" vault, you might have an archive entitled "family information."
	Each record in this archive might be a name of a family member, and then their phone number, address, or some
	other piece of pertinent information.
</p>
<h3>Can other people use this with me?</h3>
<p>
	Yes!
	You can register multiple accounts using the registration invite code at the bottom of the main menu.
	Registration invite codes are extremely time limited, so you need to create a new account immediately after copying the
	code.
</p>
<h3>How does the encryption technology work?</h3>
<p>
	There is an encryption method, and a decryption method.
	The encryption method takes a data packet, and a key.
</p>
<p>
	The application, on installation, generates a 2048-byte application key and 384-byte salt using a cryptographically secure
	random byte function.
	Key hashes are one-way hashed using Argon2.
	If that is unavailable, they are hashed using PBKDF2-SHA512 with at least 100,000 iterations.
</p>
<p>
	The application key is generally only used for encrypting session values, but could be used as a fallback if a key is not
	supplied.
	The application salt is generally only used as a fallback, as above.
	Each user, on registration, generates a 2048-byte salt using a cryptographically secure random byte function. This is a
	static salt bound to the user.
	The user's password is stored as a one-way hash using Bcrypt with a work-factor of 14.
	The user's password and salt are combined as a key hash and used to encrypt vault information.
	Each vault, on creation, has a password stored as a one-way hash using Bcrypt with a work-factor of 14.
	The vault's password and the user's salt are combined as a key hash and used to encrypt archive and record information.
</p>
<p>
	Encryption is performed through OpenSSL using a predefined cipher.
	The AES Cipher is set automatically by the application, prioritizing higher bit-length keys, and Galois/Counter Mode over
	Counter Mode.
	The initialization vector is set using a cryptographically secure random byte function and the length is set automatically
	by OpenSSL based on cipher.
	When using GCM, the tag length is 16 and is automatically generated by OpenSSL.
	When using CTR, the HMAC is done through SHA512.
</p>