CREATE TABLE `vault` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`user_id` BIGINT UNSIGNED NOT NULL,
	`name` MEDIUMBLOB NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`),
	INDEX `user_id_index` (`user_id`),
	FOREIGN KEY (`user_id`) REFERENCES user(`id`) ON DELETE CASCADE
);