CREATE TABLE `archive` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`vault_id` BIGINT UNSIGNED NOT NULL,
	`name` MEDIUMBLOB NOT NULL,
	`content` LONGBLOB NOT NULL,
	PRIMARY KEY (`id`),
	INDEX `vault_id_index` (`vault_id`),
	FOREIGN KEY (`vault_id`) REFERENCES vault(`id`) ON DELETE CASCADE
);